package com.porul.ss;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-09-10T19:00:15.752+05:30
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://porul.com/ss", name = "SimpleService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SimpleService {

    @WebResult(name = "concatResponse", targetNamespace = "http://porul.com/ss", partName = "parameters")
    @WebMethod(action = "http://porul.com/ss/NewOperation")
    public java.lang.String concat(
        @WebParam(partName = "parameters", name = "concatRequest", targetNamespace = "http://porul.com/ss")
        ConcatRequest parameters
    );
}
