package com.porul.qpaservice;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-09-14T15:02:15.615+05:30
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "QPAService", 
                  wsdlLocation = "src/main/resources/QPAService.wsdl",
                  targetNamespace = "http://www.porul.com/QPAService/") 
public class QPAService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.porul.com/QPAService/", "QPAService");
    public final static QName P1 = new QName("http://www.porul.com/QPAService/", "p1");
    static {
        URL url = QPAService_Service.class.getResource("src/main/resources/QPAService.wsdl");
        if (url == null) {
            url = QPAService_Service.class.getClassLoader().getResource("QPAService.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(QPAService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "src/main/resources/QPAService.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public QPAService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public QPAService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QPAService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public QPAService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public QPAService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public QPAService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns QPAService
     */
    @WebEndpoint(name = "p1")
    public QPAService getP1() {
        return super.getPort(P1, QPAService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QPAService
     */
    @WebEndpoint(name = "p1")
    public QPAService getP1(WebServiceFeature... features) {
        return super.getPort(P1, QPAService.class, features);
    }

}
