
package com.porul.qpaservice;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-09-14T14:50:11.598+05:30
 * Generated source version: 2.7.6
 * 
 */
 
public class QPAService_P1_Server{

    protected QPAService_P1_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new QPAServiceImpl();
        String address = "http://localhost:8080/qpas/p1";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new QPAService_P1_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
