package com.porul.qpaservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-09-14T14:50:11.567+05:30
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://www.porul.com/QPAService/", name = "QPAService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface QPAService {

    @WebResult(name = "productQueryResult", targetNamespace = "http://www.porul.com/QPAService/", partName = "parameters")
    @WebMethod(action = "http://www.porul.com/QPAService/query")
    public ProductQueryResult query(
        @WebParam(partName = "parameters", name = "productQuery", targetNamespace = "http://www.porul.com/QPAService/")
        ProductQueryComplexType parameters
    ) throws QueryInvalidQty;
}
