
package com.porul.qpaservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-09-14T14:50:11.520+05:30
 * Generated source version: 2.7.6
 */

@WebFault(name = "invalidQty", targetNamespace = "http://www.porul.com/QPAService/")
public class QueryInvalidQty extends Exception {
    
    private int invalidQty;

    public QueryInvalidQty() {
        super();
    }
    
    public QueryInvalidQty(String message) {
        super(message);
    }
    
    public QueryInvalidQty(String message, Throwable cause) {
        super(message, cause);
    }

    public QueryInvalidQty(String message, int invalidQty) {
        super(message+invalidQty);
        this.invalidQty = invalidQty;
    }

    public QueryInvalidQty(String message, int invalidQty, Throwable cause) {
        super(message, cause);
        this.invalidQty = invalidQty;
    }

    public int getFaultInfo() {
        return this.invalidQty;
    }
}
